apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: client
  annotations:
    run.googleapis.com/description: 'FinLearn App'
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: docker.io/awhooogha/client:latest
          ports:
            - name: http1
              containerPort: 3000
          env:
            - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: CLERK_SECRET_KEY
            - name: NEXT_PUBLIC_CLERK_SIGN_IN_URL
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: NEXT_PUBLIC_CLERK_SIGN_IN_URL
            - name: NEXT_PUBLIC_CLERK_SIGN_UP_URL
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: NEXT_PUBLIC_CLERK_SIGN_UP_URL
            - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
            - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 10
  traffic:
    - percent: 100
      latestRevision: true
