version: '3.8'
services:
  client:
    image: awhooogha/client:0.17.0
    build: ./client
    depends_on:
      - server
    ports:
      - 3000:3000
    env_file: ./client/.env
  server:
    image: awhooogha/server:0.17.0
    build: ./server
    ports:
      - 4000:4000
    env_file: ./server/.env
