apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: server
  annotations:
    run.googleapis.com/description: 'FinLearn API Server'
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: docker.io/awhooogha/server:latest
          ports:
            - name: http1
              containerPort: 4000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: MONGO_URI
            - name: ALPHAVANTAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: ALPHAVANTAGE_API_KEY
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 60
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /status
              port: 4000
            initialDelaySeconds: 60
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 10
  traffic:
    - percent: 100
      latestRevision: true
