name: 'Group 1 CI'
on:
  push:
    branches:
      - group-1
env:
  NODE_VERSION: 18
  SERVER_REPORTS_FOLDER: server/reports
jobs:
  build-server:
    name: 'Build Server Image'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: '${{ env.NODE_VERSION }}'

      - name: Checkout HEAD Commit
        uses: actions/checkout@v3.5.3
        with:
          ref: '${{ github.head_ref }}'

      - name: 'DockerHub Login'
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.GP1_DOCKERHUB_USERNAME }}
          password: ${{ secrets.GP1_DOCKER_TOKEN }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Build and Push
        uses: docker/build-push-action@v4.1.1
        with:
          context: '{{defaultContext}}:server'
          file: Dockerfile
          push: true
          tags: ${{ secrets.GP1_DOCKERHUB_USERNAME }}/server:latest

  deploy-server:
    name: 'Deploy Server Image'
    runs-on: ubuntu-latest
    needs: build-server
    steps:
      - name: Checkout HEAD Commit
        uses: actions/checkout@v3.5.3
        with:
          ref: '${{ github.head_ref }}'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          service_account: ${{ secrets.GP1_GCP_SA_EMAIL }}
          credentials_json: ${{ secrets.GP1_GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1.0.2
        with:
          metadata: ./server/service.yaml
          region: ${{ secrets.GP1_GCP_REGION }}

  test-server:
    name: 'Test Server Deployment'
    runs-on: ubuntu-latest
    needs: deploy-server
    steps:
      - name: Checkout HEAD Commit
        uses: actions/checkout@v3.5.3
        with:
          ref: '${{ github.head_ref }}'

      - name: Create Reports Directory
        run: mkdir ${{ env.SERVER_REPORTS_FOLDER }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'npm'

      - name: Install newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Learning Collection
        run: newman run "28563069-fcd6a167-f310-4f52-8dc1-897aebf4fe22" -e "28563069-f6df5499-f91c-410a-970b-531f5700edfb" --postman-api-key ${{ secrets.GP1_POSTMAN_KEY }} --delay-request 5 -r htmlextra --reporter-htmlextra-export ${{ env.SERVER_REPORTS_FOLDER }}/learning.html --reporter-htmlextra-displayProgressBar --reporter-htmlextra-browserTitle "Learning Report" --reporter-htmlextra-title "Learning Results"

      - name: Run Research Collection
        run: newman run "28563069-4f8a9d7f-f211-4250-a70a-d5af7fe5ffed" -e "28563069-f6df5499-f91c-410a-970b-531f5700edfb" --postman-api-key ${{ secrets.GP1_POSTMAN_KEY }} --delay-request 5 -r htmlextra --reporter-htmlextra-export ${{ env.SERVER_REPORTS_FOLDER }}/research.html --reporter-htmlextra-displayProgressBar --reporter-htmlextra-browserTitle "Research Report" --reporter-htmlextra-title "Research Results"

      - name: Publish Postamn Reports
        uses: actions/download-artifact@v3.0.2
        with:
          name: Server Reports
          path: ${{ env.SERVER_REPORTS_FOLDER }}

  build-client:
    name: 'Build Client Image'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: '${{ env.NODE_VERSION }}'

      - name: Checkout HEAD Commit
        uses: actions/checkout@v3.5.3
        with:
          ref: '${{ github.head_ref }}'

      - name: 'DockerHub Login'
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.GP1_DOCKERHUB_USERNAME }}
          password: ${{ secrets.GP1_DOCKER_TOKEN }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Build and Push
        uses: docker/build-push-action@v4.1.1
        with:
          build-args: SEVER_URL=${{ secrets.GP1_SERVER_URL }}
          context: '{{defaultContext}}:client'
          file: Dockerfile
          push: true
          tags: ${{ secrets.GP1_DOCKERHUB_USERNAME }}/client:latest

  deploy-client:
    name: 'Deploy Client Image'
    runs-on: ubuntu-latest
    needs: [build-client, deploy-server]
    steps:
      - name: Checkout HEAD Commit
        uses: actions/checkout@v3.5.3
        with:
          ref: '${{ github.head_ref }}'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          service_account: ${{ secrets.GP1_GCP_SA_EMAIL }}
          credentials_json: ${{ secrets.GP1_GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1.0.2
        with:
          metadata: ./client/service.yaml
          region: ${{ secrets.GP1_GCP_REGION }}
