name: 'CI'
on:
  push:
    branches:
      - group-1
env:
  NODE_VERSION: 18
jobs:
  server:
    name: 'Server Image'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: '${{ env.NODE_VERSION }}'

      - name: Checkout HEAD Commit
        uses: actions/checkout@v3.5.3
        with:
          ref: '${{ github.head_ref }}'

      - name: 'DockerHub Login'
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.GP1_DOCKERHUB_USERNAME }}
          password: ${{ secrets.GP1_DOCKER_TOKEN }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Build and Push
        uses: docker/build-push-action@v4.1.1
        with:
          context: '{{defaultContext}}:server'
          file: Dockerfile
          push: true
          tags: ${{ secrets.GP1_DOCKERHUB_USERNAME }}/server:latest

  client:
    name: 'Client Image'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: '${{ env.NODE_VERSION }}'

      - name: Checkout HEAD Commit
        uses: actions/checkout@v3.5.3
        with:
          ref: '${{ github.head_ref }}'

      - name: 'DockerHub Login'
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.GP1_DOCKERHUB_USERNAME }}
          password: ${{ secrets.GP1_DOCKER_TOKEN }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Build and Push
        uses: docker/build-push-action@v4.1.1
        with:
          context: '{{defaultContext}}:client'
          file: Dockerfile
          push: true
          tags: ${{ secrets.GP1_DOCKERHUB_USERNAME }}/client:latest
