name: 'Group 1 CI'
on:
  push:
    branches:
      - group-1
env:
  NODE_VERSION: 18
jobs:
  build-server:
    name: 'Build Server Image'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: '${{ env.NODE_VERSION }}'

      - name: Checkout HEAD Commit
        uses: actions/checkout@v3.5.3
        with:
          ref: '${{ github.head_ref }}'

      - name: 'DockerHub Login'
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.GP1_DOCKERHUB_USERNAME }}
          password: ${{ secrets.GP1_DOCKER_TOKEN }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Build and Push
        uses: docker/build-push-action@v4.1.1
        with:
          context: '{{defaultContext}}:server'
          file: Dockerfile
          push: true
          tags: ${{ secrets.GP1_DOCKERHUB_USERNAME }}/server:latest

  deploy-server:
    name: 'Deploy Server Image'
    runs-on: ubuntu-latest
    needs: build-server
    steps:
      - name: Checkout HEAD Commit
        uses: actions/checkout@v3.5.3
        with:
          ref: '${{ github.head_ref }}'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          service_account: ${{ secrets.GP1_GCP_SA_EMAIL }}
          credentials_json: ${{ secrets.GP1_GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1.0.2
        with:
          metadata: ./server/service.yaml
          region: ${{ secrets.GP1_GCP_REGION }}

  build-client:
    name: 'Build Client Image'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: '${{ env.NODE_VERSION }}'

      - name: Checkout HEAD Commit
        uses: actions/checkout@v3.5.3
        with:
          ref: '${{ github.head_ref }}'

      - name: 'DockerHub Login'
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.GP1_DOCKERHUB_USERNAME }}
          password: ${{ secrets.GP1_DOCKER_TOKEN }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Build and Push
        uses: docker/build-push-action@v4.1.1
        with:
          build-args: SEVER_URL=${{ secrets.GP1_SERVER_URL }}
          context: '{{defaultContext}}:client'
          file: Dockerfile
          push: true
          tags: ${{ secrets.GP1_DOCKERHUB_USERNAME }}/client:latest

  deploy-client:
    name: 'Deploy Client Image'
    runs-on: ubuntu-latest
    needs: [build-client, deploy-server]
    steps:
      - name: Checkout HEAD Commit
        uses: actions/checkout@v3.5.3
        with:
          ref: '${{ github.head_ref }}'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          service_account: ${{ secrets.GP1_GCP_SA_EMAIL }}
          credentials_json: ${{ secrets.GP1_GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1.0.2
        with:
          metadata: ./client/service.yaml
          region: ${{ secrets.GP1_GCP_REGION }}
